export const VIDEO_BG_CONTRACT_ADDRESS = '0x19B11a0520cA412A70F6Ba2c030DBa542Fc04A84' as const;

export const VIDEO_BG_ABI = [
  { type: 'constructor', inputs: [{ name: '_wmon', type: 'address' }, { name: '_treasury', type: 'address' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'BASELINE_DURATION', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'BPS_DENOMINATOR', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'MAX_BASE_PRICE', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'MAX_DURATION', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'MIN_DURATION', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'basePrice', inputs: [{ name: '', type: 'uint8' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'getAllBasePrices', inputs: [], outputs: [{ type: 'uint256[3]' }], stateMutability: 'view' },
  { type: 'function', name: 'getPrice', inputs: [{ name: 'style', type: 'uint8' }, { name: 'res', type: 'uint8' }, { name: 'duration', type: 'uint256' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'owner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'pendingOwner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'treasury', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'wmon', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'totalCollected', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'resolutionMultiplier', inputs: [{ name: '', type: 'uint8' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'payWithMON', inputs: [{ name: 'style', type: 'uint8' }, { name: 'res', type: 'uint8' }, { name: 'duration', type: 'uint256' }], outputs: [{ type: 'bytes32' }], stateMutability: 'payable' },
  { type: 'function', name: 'payWithWMON', inputs: [{ name: 'style', type: 'uint8' }, { name: 'res', type: 'uint8' }, { name: 'duration', type: 'uint256' }], outputs: [{ type: 'bytes32' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'setBasePrice', inputs: [{ name: 'style', type: 'uint8' }, { name: 'newPrice', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'setResolutionMultiplier', inputs: [{ name: 'res', type: 'uint8' }, { name: 'newMult', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'setTreasury', inputs: [{ name: 'newTreasury', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'rescueTokens', inputs: [{ name: 'token', type: 'address' }, { name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'acceptOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'transferOwnership', inputs: [{ name: 'newOwner', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'event', name: 'GenerationPaid', inputs: [{ name: 'requestId', type: 'bytes32', indexed: true }, { name: 'user', type: 'address', indexed: true }, { name: 'style', type: 'uint8' }, { name: 'resolution', type: 'uint8' }, { name: 'duration', type: 'uint256' }, { name: 'price', type: 'uint256' }, { name: 'nativePay', type: 'bool' }, { name: 'timestamp', type: 'uint256' }] },
  { type: 'event', name: 'BasePriceUpdated', inputs: [{ name: 'style', type: 'uint8', indexed: true }, { name: 'newPrice', type: 'uint256' }] },
  { type: 'event', name: 'ResolutionMultiplierUpdated', inputs: [{ name: 'res', type: 'uint8', indexed: true }, { name: 'newMult', type: 'uint256' }] },
  { type: 'event', name: 'TreasuryUpdated', inputs: [{ name: 'newTreasury', type: 'address' }] },
  { type: 'event', name: 'OwnershipTransferStarted', inputs: [{ name: 'previousOwner', type: 'address', indexed: true }, { name: 'newOwner', type: 'address', indexed: true }] },
  { type: 'event', name: 'OwnershipTransferred', inputs: [{ name: 'previousOwner', type: 'address', indexed: true }, { name: 'newOwner', type: 'address', indexed: true }] },
] as const;
